version: '3.8'

volumes:
  django_media: {}
  django_static: {}

services:
  nginx:
    container_name : nginx
    image: nginx:1.23.2
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - django_media:/media/
      - django_static:/static/
    restart: always

  blue-backend:
    container_name: blue-backend
    image: wogur981208/django:latest
    entrypoint: sh -c "poetry run python manage.py collectstatic --no-input && poetry run python manage.py migrate && poetry run gunicorn config.wsgi --workers=5 -b 0.0.0.0:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - django_media:/app/media/
      - django_static:/app/static/
    expose:
      - 8000

  green-backend:
    container_name: green-backend
    image: wogur981208/django:latest
    entrypoint: sh -c "poetry run python manage.py collectstatic --no-input && poetry run python manage.py migrate && poetry run gunicorn config.wsgi --workers=5 -b 0.0.0.0:8001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - django_media:/app/media/
      - django_static:/app/static/
    restart: always
    expose:
      - 8001
