version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql:8.1
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=github_actions
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/:/var/lib/mysql

  django:
    container_name: django
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    environment:
      - GITHUB_WORKFLOW=True
    command: poetry run python manage.py runserver 0.0.0.0:8000 --settings=config.settings.local
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    restart: on-failure
